- name: Collect interface status from R1
  hosts: routers
  gather_facts: no
  connection: network_cli

  tasks:
  - name: Show IP Interface Brief
    cisco.ios.ios_command:
      commands:
        - show ip interface brief
    register: output

  - name: Display results
    debug:
      msg: "{{ output.stdout[0] }}"

  - name: Save output to file
    copy: 
      content: "{{ output.stdout[0] }}"
      dest: "./outputs/{{ inventory_hostname }}_show_ip_int_brief.txt"
